# Generated by Django 3.0.6 on 2020-08-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoscore', '0002_cell_isselected'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='slug',
            field=models.SlugField(default='s'),
        ),
    ]
